[project]
name = "WSGIEchoIP"
dynamic = ["version"]
license = {file = "LICENSE"}

[tool.setuptools.dynamic]
version = {attr = "WSGIEchoIP.__version__"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
